[versions]
loom = "1.10.+"
githubRelease = "2.4.1"
minotaur = "2.+"

mc = "1.21.5"
fl = "0.15.11"
yarn = "1.21.5+build.1"
fapi = "0.128.2+1.21.5"

switchy = "2.9.11+1.21"

placeholder = "2.6.4+1.21.5"
styledChat = "2.8.0+1.21.5"
playerData = "0.7.0+1.21.5"
permissionsApi = "0.3.3"
predicate = "0.6.0+1.21.2"

[plugins]
loom = { id = "fabric-loom", version.ref = "loom" }
githubRelease = { id = "com.github.breadmoirai.github-release", version.ref = "githubRelease" }
minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }

[libraries]
mc = { group = "mojang", name = "minecraft", version.ref = "mc" }
fl = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fl" }
yarn = { group = "net.fabricmc", name = "yarn", version.ref = "yarn" }
fapi = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fapi" }

switchyCore = { group = "folk.sisby", name = "switchy-core", version.ref = "switchy" }
switchyClient = { group = "folk.sisby", name = "switchy-client", version.ref = "switchy" }
switchyUI = { group = "folk.sisby", name = "switchy-ui", version.ref = "switchy" }
switchyCompat = { group = "folk.sisby", name = "switchy-compat", version.ref = "switchy" }

placeholder = { group = "eu.pb4", name = "placeholder-api", version.ref = "placeholder" }
styledChat = { group = "maven.modrinth", name = "styled-chat", version.ref = "styledChat" }
playerData = { group = "eu.pb4", name = "player-data-api", version.ref = "playerData" }
permissionsApi = { group = "me.lucko", name = "fabric-permissions-api", version.ref = "permissionsApi" }
predicate = { group = "eu.pb4", name = "predicate-api", version.ref = "predicate" }
